
import { TranslationSchema, Category } from './types';

export const CATEGORIES: Category[] = [
  'food',
  'transport',
  'bills',
  'entertainment',
  'shopping',
  'health',
  'salary',
  'other'
];

export const TRANSLATIONS: Record<string, TranslationSchema> = {
  en: {
    app_name: "Budget Tracker",
    home: "Home",
    add_transaction: "Add Transaction",
    all_transactions: "All Transactions",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    light_theme: "Light",
    dark_theme: "Dark",
    system_theme: "System Default",
    amount: "Amount",
    type: "Type",
    income: "Income",
    expense: "Expense",
    category: "Category",
    date: "Date",
    note: "Note",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    total_income: "Total Income",
    total_expenses: "Total Expenses",
    net_balance: "Net Balance",
    recent_transactions: "Recent Transactions",
    no_transactions: "No transactions yet.",
    import_data: "Import JSON",
    export_data: "Export JSON",
    import_success: "Transactions imported successfully!",
    invalid_file: "Invalid file format.",
    confirm_delete_title: "Delete Transaction?",
    confirm_delete_message: "Are you sure you want to delete this transaction? This action cannot be undone.",
    categories: {
      food: "Food",
      transport: "Transport",
      bills: "Bills",
      entertainment: "Entertainment",
      shopping: "Shopping",
      health: "Health",
      salary: "Salary",
      other: "Other"
    },
    errors: {
      amount_required: "Amount is required",
      type_required: "Transaction type is required"
    }
  },
  ar: {
    app_name: "متتبع الميزانية",
    home: "الرئيسية",
    add_transaction: "إضافة معاملة",
    all_transactions: "كل المعاملات",
    settings: "الإعدادات",
    language: "اللغة",
    theme: "السمة",
    light_theme: "فاتح",
    dark_theme: "داكن",
    system_theme: "افتراضي النظام",
    amount: "المبلغ",
    type: "النوع",
    income: "دخل",
    expense: "مصروف",
    category: "الفئة",
    date: "التاريخ",
    note: "ملاحظة",
    save: "حفظ",
    cancel: "إلغاء",
    edit: "تعديل",
    delete: "حذف",
    total_income: "إجمالي الدخل",
    total_expenses: "إجمالي المصروفات",
    net_balance: "صافي الرصيد",
    recent_transactions: "أحدث المعاملات",
    no_transactions: "لا توجد معاملات بعد.",
    import_data: "استيراد JSON",
    export_data: "تصدير JSON",
    import_success: "تم استيراد المعاملات بنجاح!",
    invalid_file: "تنسيق ملف غير صالح.",
    confirm_delete_title: "حذف المعاملة؟",
    confirm_delete_message: "هل أنت متأكد أنك تريد حذف هذه المعاملة؟ لا يمكن التراجع عن هذا الإجراء.",
    categories: {
      food: "طعام",
      transport: "نقل",
      bills: "فواتير",
      entertainment: "ترفيه",
      shopping: "تسوق",
      health: "صحة",
      salary: "راتب",
      other: "أخرى"
    },
    errors: {
      amount_required: "المبلغ مطلوب",
      type_required: "نوع المعاملة مطلوب"
    }
  },
  fr: {
    app_name: "Gestionnaire de Budget",
    home: "Accueil",
    add_transaction: "Ajouter une transaction",
    all_transactions: "Les transactions",
    settings: "Paramètres",
    language: "Langue",
    theme: "Thème",
    light_theme: "Clair",
    dark_theme: "Sombre",
    system_theme: "Par défaut du système",
    amount: "Montant",
    type: "Type",
    income: "Revenu",
    expense: "Dépense",
    category: "Catégorie",
    date: "Date",
    note: "Note",
    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    delete: "Supprimer",
    total_income: "Revenu total",
    total_expenses: "Dépenses totales",
    net_balance: "Solde net",
    recent_transactions: "Transactions récentes",
    no_transactions: "Aucune transaction pour l'instant.",
    import_data: "Importer JSON",
    export_data: "Exporter JSON",
    import_success: "Transactions importées avec succès !",
    invalid_file: "Format de fichier invalide.",
    confirm_delete_title: "Supprimer la transaction ?",
    confirm_delete_message: "Êtes-vous sûr de vouloir supprimer cette transaction ? Cette action est irréversible.",
    categories: {
      food: "Nourriture",
      transport: "Transport",
      bills: "Factures",
      entertainment: "Divertissement",
      shopping: "Achats",
      health: "Santé",
      salary: "Salaire",
      other: "Autre"
    },
    errors: {
      amount_required: "Le montant est requis",
      type_required: "Le type de transaction est requis"
    }
  }
};
